fixtures:
  forge_modules:
    accounts: 'puppetlabs/accounts'
    activemq: 'puppetlabs/activemq'
    archive: 'puppet/archive'
    augeasproviders_core: 'herculesteam/augeasproviders_core'
    augeasproviders_sysctl: 'herculesteam/augeasproviders_sysctl'
    apache: 'puppetlabs/apache'
    apt: 'puppetlabs/apt'
    aptly: 'gdsoperations/aptly'
    augeas_core:
      repo: 'puppetlabs/augeas_core'
      puppet_version: '>= 6.0.0'
    carbon_c_relay: 'mlambrichs/carbon_c_relay'
    concat: 'puppetlabs/concat'
    consul: 'KyleAnderson/consul'
    collectd: 'puppet/collectd'
    composer: 'willdurand/composer'
    cron: 'puppet/cron'
    cron_core:
      repo: 'puppetlabs/cron_core'
      puppet_version: '>= 6.0.0'
    datacat: 'richardc/datacat'
    dns: 'theforeman/dns'
    docker: 'puppetlabs/docker'
    dnsmasq: 'saz/dnsmasq'
    elasticsearch:
      repo: 'elastic/elasticsearch'
      ref: '5.5.0'
    epel: 'puppet/epel'
    extlib: 'puppet/extlib'
    fail2ban: 'puppet/fail2ban'
    file_concat: 'electrical/file_concat'
    firewall: 'puppetlabs/firewall'
    foreman: 'theforeman/foreman'
    foreman_proxy: 'theforeman/foreman_proxy'
    gcc: 'puppetlabs/gcc'
    git: 'puppetlabs/git'
    gitlab: 'puppet/gitlab'
    grafana: 'puppet/grafana'
    haproxy: 'puppetlabs/haproxy'
    icinga: 'icinga/icinga'
    icinga2: 'icinga/icinga2'
    icingaweb2: 'icinga/icingaweb2'
    inifile: 'puppetlabs/inifile'
    java: 'puppetlabs/java'
    jenkins: 'puppet/jenkins'
    kafka: 'puppet/kafka'
    kibana:
      repo: 'elastic/kibana'
      ref: '5.2.0'
    letsencrypt: 'puppet/letsencrypt'
    logstash:
      repo: 'elastic/logstash'
      ref: '5.3.0'
    lvm: 'puppetlabs/lvm'
    mongodb: 'puppet/mongodb'
    mount_core: 'puppetlabs/mount_core'
    mcollective: 'puppet/mcollective'
    memcached: 'saz/memcached'
    mysql: 'puppetlabs/mysql'
    neo4j: 'mlambrichs/neo4j'
    nexus: 'hubspot/nexus'
    nginx: 'puppet/nginx'
    nodejs: 'puppet/nodejs'
    nomad: 'puppet/nomad'
    ntp: 'puppetlabs/ntp'
    php: 'puppet/php'
    postgresql: 'puppetlabs/postgresql'
    prometheus: 'puppet/prometheus'
    puppet: 'theforeman/puppet'
    puppet_authorization: 'puppetlabs/puppet_authorization'
    puppetdb: 'puppetlabs/puppetdb'
    python: 'puppet/python'
    r10k: 'puppet/r10k'
    redis: 'puppet/redis'
    remote_file: 'lwf/remote_file'
    resolv_conf: 'saz/resolv_conf'
    ruby:    'puppetlabs/ruby'
    rundeck: 'puppet/rundeck'
    selinux: 'puppet/selinux'
    staging: 'puppet/staging'
    stdlib: 'puppetlabs/stdlib'
    sudo: 'saz/sudo'
    statsd: 'jdowning/statsd'
    systemd: 'camptocamp/systemd'
    sysctl: 'thias/sysctl'
    transition: 'puppetlabs/transition'
    vault: 'jsok/vault'
    wget: 'puppet/wget'
    yum: 'puppet/yum'
    yumrepo_core:
      repo: 'puppetlabs/yumrepo_core'
      puppet_version: '>= 6.0.0'
    zookeeper: 'deric/zookeeper'
  repositories:
    carbon: 'https://github.com/mlambrichs/puppet-carbon'
    carbon_relay_ng: 'https://github.com/mlambrichs/puppet-carbon_relay_ng.git'
    example: 'https://github.com/attachmentgenie/attachmentgenie-example.git'
    flink: 'https://github.com/attachmentgenie/attachmentgenie-flink.git'
    graphite_web: 'https://github.com/attachmentgenie/puppet-graphite_web.git'
    influxdb: 'https://github.com/dgolja/golja-influxdb.git'
    locales: 'https://github.com/attachmentgenie/attachmentgenie-locales.git'
    loki: 'https://github.com/attachmentgenie/attachmentgenie-loki.git'
    mailhog: 'https://github.com/attachmentgenie/attachmentgenie-mailhog.git'
    minio: 'https://github.com/kogitoapp/puppet-minio'
    ssh: 'https://github.com/attachmentgenie/attachmentgenie-ssh.git'
    timezone: 'https://github.com/attachmentgenie/attachmentgenie-timezone.git'
    traefik: 'https://github.com/attachmentgenie/puppet-traefik.git'
    traefik2: 'https://github.com/attachmentgenie/attachmentgenie-traefik2.git'
    tempo: 'https://github.com/attachmentgenie/attachmentgenie-tempo.git'
    uwsgi: 'https://github.com/rvdh/puppet-uwsgi.git'
